name: AWS SSO deploy

env:
  TEMPLATE_FILENAME: aws_sso/aws_sso_access.yml
  AWS_STACK_NAME: aws-sso-access

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    paths:
      - '.github/workflows/aws_sso_setup.yml'
      - 'aws_sso/aws_sso_access.yml'
      - '!**/*.md'
  push:
    branches: [master]
    paths:
      - '.github/workflows/aws_sso_setup.yml'
      - 'aws_sso/aws_sso_access.yml'
      - '!**/*.md'
permissions:
  id-token: write   # for AWS access via OIDC
  contents: read    # This is required for actions/checkout@v3

jobs:
  deploy-aws-sso:
    name: AWS SSO Deploy
    runs-on: ubuntu-latest
    # Only run this job if the PR is labeled with 'deploy-pr' or if the push is to master
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'deploy-pr'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials for deployment environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWESOME_AWS_DEPLOY_ROLE_ROOT }}
          aws-region: eu-central-1

      - name: Test AWS access credentials for AWS account
        run: aws sts get-caller-identity

      - name: Download aws-cloudformation/rain
        run: |
          gh release download -R aws-cloudformation/rain --pattern '*_linux-amd64.zip' -D $RUNNER_TOOL_CACHE v1.16.1
          unzip -ojq $RUNNER_TOOL_CACHE/*.zip -d $RUNNER_TOOL_CACHE
          echo "$RUNNER_TOOL_CACHE" >> $GITHUB_PATH
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Deploy Cloudformation template to AWS account
        run: rain deploy $TEMPLATE_FILENAME $AWS_STACK_NAME -y
