name: Bastion build and deploy

env:
  TEMPLATE_FILENAME: awesome-bastion/awesome-bastion.yml
  AWS_STACK_NAME: awesome-bastion
  REPOSITORY: awesome-bastion

on:
  workflow_call:
    inputs:
      AWS_ACCOUNT_STAGE:
        required: true
        type: string
        description: 'The environment to deploy to'
      AWS_ROLE_TO_ASSUME:
        required: true
        type: string
        description: 'The AWS role to assume for deployment'

permissions:
  id-token: write   # for AWS access via OIDC
  contents: read    # This is required for actions/checkout@v3

jobs:
  deploy:
    name: Deploy to ${{ inputs.AWS_ACCOUNT_STAGE }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials for deployment environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Test AWS access credentials for  ${{ inputs.AWS_ACCOUNT_STAGE }} account
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists, create if not
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          aws ecr describe-repositories --repository-names "${REPOSITORY}" || aws ecr create-repository --repository-name "${REPOSITORY}"

      - name: Construct image URL
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: echo IMAGE_URL="${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}" >> "$GITHUB_ENV"

      - name: Build and tag docker image
        run: docker build -t ${IMAGE_URL} awesome-bastion

      - name: Push docker image to Amazon ECR
        run: docker push ${IMAGE_URL}

      - name: Download aws-cloudformation/rain
        run: |
          gh release download -R aws-cloudformation/rain --pattern '*_linux-amd64.zip' -D $RUNNER_TOOL_CACHE v1.16.1
          unzip -ojq $RUNNER_TOOL_CACHE/*.zip -d $RUNNER_TOOL_CACHE
          echo "$RUNNER_TOOL_CACHE" >> $GITHUB_PATH
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Deploy Cloudformation template
        run: rain deploy $TEMPLATE_FILENAME $AWS_STACK_NAME -y --params ServiceName=bastion,ImageUrl=${IMAGE_URL}
