# Copyright 2025 Luka KladariÄ‡, Chaos Guru
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Web test and deploy on PR

env:
  TEMPLATE_FILENAME: awesome-web/awesome-web.yml
  AWS_STACK_NAME: awesome-web
  # AZ deployment configuration (must match VPC stack settings)
  DEPLOY_AZ_ONE: 1
  DEPLOY_AZ_TWO: 1
  DEPLOY_AZ_THREE: 0

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
    paths:
      - '.github/workflows/web_*.yml'
      - 'awesome-web/*.yml'
      - '!**/*.md'

permissions:
  id-token: write   # for AWS access via OIDC
  contents: read    # This is required for actions/checkout@v3
  pull-requests: write # Needed to comment on PRs

jobs:
  deploy-awesome-web:
    name: Web test and maybe deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials for deployment environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWESOME_AWS_DEPLOY_ROLE_DEV }}
          aws-region: ${{ vars.AWESOME_AWS_DEFAULT_REGION }}

      - name: Test AWS access credentials for dev account
        run: aws sts get-caller-identity

      - name: Ensure ECS service-linked role exists
        run: aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com || true

      - uses: allixsenos/install-rain@v1

      - name: Create Cloudformation ChangeSet
        run: rain deploy --no-exec $TEMPLATE_FILENAME $AWS_STACK_NAME -y --params DeployAZOne=$DEPLOY_AZ_ONE,DeployAZTwo=$DEPLOY_AZ_TWO,DeployAZThree=$DEPLOY_AZ_THREE

      - name: Get latest changeset ID
        run: aws cloudformation list-change-sets --stack-name $AWS_STACK_NAME --query 'Summaries | sort_by(@, &CreationTime) | [-1].ChangeSetId' --output text > changeset-id

      - name: Get changeset diff
        run: aws cloudformation describe-change-set --change-set-name $(cat changeset-id) > describe-change-set.json

      - name: Delete changeset
        run: aws cloudformation delete-change-set --change-set-name $(cat changeset-id)

      - name: Process diff into Markdown table
        run: jq -r '.Changes[] | [.ResourceChange.Action, .ResourceChange.LogicalResourceId, .ResourceChange.ResourceType, .ResourceChange.Replacement] | @tsv' describe-change-set.json | awk 'BEGIN {print "| Action | LogicalResourceId | ResourceType | Replacement |"; print "|--------|-----------------|--------------|-------------|"} {print "| " $1 " | " $2 " | " $3 " | " $4 " |"}' > changeset.diff

      - name: Preview changeset
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request' && (success() || failure())
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filePath: changeset.diff
          comment_tag: preview
          mode: recreate

      - name: Deploy Cloudformation template to dev account
        if: github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'deploy-pr')
        run: rain deploy $TEMPLATE_FILENAME $AWS_STACK_NAME -y --params DeployAZOne=$DEPLOY_AZ_ONE,DeployAZTwo=$DEPLOY_AZ_TWO,DeployAZThree=$DEPLOY_AZ_THREE | tee rain-deploy.log

      - name: Rain Deploy log
        uses: thollander/actions-comment-pull-request@v2
        if: github.event.pull_request.state == 'open' && contains(github.event.pull_request.labels.*.name, 'deploy-pr') && (success() || failure())
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filePath: rain-deploy.log
          comment_tag: raindeploy
          mode: recreate
